/**
 * Cross-language parity for LUT sampling.
 *
 * The look engine implements LUT sampling three times: Python (backend/lut.py),
 * TypeScript (src/look/lut.ts) and GLSL (src/look/shader.ts). Divergence would mean the
 * on-device photo looks different from the backend render, which is exactly the class of
 * bug that's invisible until someone compares two images side by side.
 *
 * The fixture is generated by backend/tools/gen_lut_fixture.py.
 */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';

import { gridFromStrip, identityGrid, sampleLut, type LutGrid, type Rgb } from '../look/lut';

const here = dirname(fileURLToPath(import.meta.url));
const fixture = JSON.parse(
  readFileSync(join(here, 'fixtures', 'lutParity.json'), 'utf-8'),
) as {
  camera: string;
  size: number;
  strip: number[];
  samples: number[][];
  expected: number[][];
};

function fixtureGrid(): LutGrid {
  const size = fixture.size;
  return gridFromStrip(Uint8Array.from(fixture.strip), size * size, size);
}

test('fixture is well formed', () => {
  const size = fixture.size;
  assert.equal(fixture.strip.length, size * size * size * 3);
  assert.equal(fixture.samples.length, fixture.expected.length);
  assert.ok(fixture.samples.length >= 10);
});

test('TypeScript sampling matches the Python implementation', () => {
  const grid = fixtureGrid();
  const worst: { rgb: number[]; err: number } = { rgb: [], err: 0 };

  for (let i = 0; i < fixture.samples.length; i++) {
    const input = fixture.samples[i] as Rgb;
    const got = sampleLut(grid, input);
    const want = fixture.expected[i];
    for (let c = 0; c < 3; c++) {
      const err = Math.abs(got[c] - want[c]);
      if (err > worst.err) {
        worst.err = err;
        worst.rgb = input;
      }
    }
  }

  // Python rounds to uint8 on output; allow a single level of rounding difference.
  assert.ok(
    worst.err <= 1.5,
    `worst channel error ${worst.err.toFixed(2)} at rgb(${worst.rgb.join(',')}) — ` +
      'TypeScript and Python LUT sampling have diverged',
  );
});

test('identity LUT returns the input colour', () => {
  const grid = identityGrid(17);
  for (const rgb of [[0, 0, 0], [255, 255, 255], [128, 64, 32], [17, 200, 43]] as Rgb[]) {
    const out = sampleLut(grid, rgb);
    for (let c = 0; c < 3; c++) {
      assert.ok(Math.abs(out[c] - rgb[c]) <= 1.5, `identity changed ${rgb} -> ${out}`);
    }
  }
});

test('identityGrid matches the backend lattice ordering', () => {
  // Red varies fastest: entry 1 differs from entry 0 in red only.
  const g = identityGrid(4);
  assert.deepEqual([g.data[0], g.data[1], g.data[2]], [0, 0, 0]);
  assert.ok(g.data[3] > 0, 'red should advance first');
  assert.equal(g.data[4], 0);
  assert.equal(g.data[5], 0);
  // After `size` entries green advances.
  assert.ok(g.data[4 * 3 + 1] > 0, 'green should advance after a full red row');
});

test('sampling clamps out-of-range input instead of reading out of bounds', () => {
  const grid = identityGrid(9);
  for (const rgb of [[-50, 0, 0], [300, 300, 300], [NaN, 0, 0]] as Rgb[]) {
    const out = sampleLut(grid, rgb);
    for (const v of out) assert.ok(Number.isFinite(v), `non-finite output for ${rgb}`);
  }
});

test('gridFromStrip accepts RGBA input by dropping alpha', () => {
  const size = 4;
  const rgb = identityGrid(size);
  const rgba = new Uint8Array(size * size * size * 4);
  for (let i = 0; i < size * size * size; i++) {
    rgba[i * 4] = rgb.data[i * 3];
    rgba[i * 4 + 1] = rgb.data[i * 3 + 1];
    rgba[i * 4 + 2] = rgb.data[i * 3 + 2];
    rgba[i * 4 + 3] = 255;
  }
  const grid = gridFromStrip(rgba, size * size, size);
  assert.deepEqual([...grid.data], [...rgb.data]);
});

test('gridFromStrip rejects wrong dimensions', () => {
  assert.throws(() => gridFromStrip(new Uint8Array(12), 5, 4));
});
