"""Generate the cross-language LUT parity fixture.

The on-device look engine reimplements LUT sampling in TypeScript (and again in GLSL).
This writes a fixture of input colours and the Python implementation's outputs so the
TypeScript version can be asserted against it in CI, catching drift between the two.

    cd backend && python tools/gen_lut_fixture.py
"""

import json
import sys
from pathlib import Path

import numpy as np
from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import lut  # noqa: E402

OUT = Path(__file__).resolve().parents[2] / "mobile" / "src" / "__tests__" / "fixtures" / "lutParity.json"

# A spread of colours: neutrals, primaries, saturated corners and awkward mid-tones.
SAMPLES = [
    (0, 0, 0), (255, 255, 255), (128, 128, 128), (64, 64, 64), (192, 192, 192),
    (255, 0, 0), (0, 255, 0), (0, 0, 255),
    (255, 255, 0), (0, 255, 255), (255, 0, 255),
    (200, 150, 100), (30, 60, 90), (17, 200, 43), (250, 5, 130),
    (99, 99, 1), (1, 1, 254), (137, 42, 211), (73, 181, 96), (240, 230, 210),
]

CAMERA = "ccd"
SIZE = lut.DEFAULT_SIZE


def main() -> int:
    grid = lut.bake_camera_lut(CAMERA, SIZE)

    # Sample each colour through the Python interpolator by rendering 1x1 images.
    outputs = []
    for rgb in SAMPLES:
        img = Image.new("RGB", (1, 1), rgb)
        out = lut.apply_lut(img, grid, SIZE)
        outputs.append([int(v) for v in np.asarray(out).reshape(3)])

    strip = np.clip(grid, 0, 255).astype(np.uint8).reshape(SIZE, SIZE * SIZE, 3)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        json.dumps(
            {
                "camera": CAMERA,
                "size": SIZE,
                "note": "Generated by backend/tools/gen_lut_fixture.py — do not edit by hand.",
                "strip": strip.reshape(-1).tolist(),
                "samples": [list(s) for s in SAMPLES],
                "expected": outputs,
            }
        ),
        encoding="utf-8",
    )
    print(f"wrote {OUT} ({OUT.stat().st_size / 1024:.1f} KB, {len(SAMPLES)} samples)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
