/**
 * LUT strip decoding and trilinear sampling — pure TypeScript, no native imports.
 *
 * This mirrors `backend/lut.py` exactly so the two can be checked against each other
 * (see __tests__/lut.test.ts, which asserts parity against fixtures generated by the
 * Python implementation). The GPU shader in `shader.ts` performs the same maths; keeping
 * a CPU version means the interpolation can be unit-tested without a device.
 */

export type LutGrid = {
  /** Flat RGB triples, red varying fastest, length = size ** 3 * 3. */
  data: Uint8Array;
  size: number;
};

export type Rgb = [number, number, number];

/**
 * Decode a LUT strip image into a grid.
 *
 * Strip layout is (size*size) x size: `size` blue slices laid left to right, each a
 * size x size tile of red (x) by green (y).
 */
export function gridFromStrip(pixels: Uint8Array, width: number, height: number): LutGrid {
  const size = height;
  if (width !== size * size) {
    throw new Error(`LUT strip must be ${size * size}x${size}, got ${width}x${height}`);
  }
  const expected = size * size * size * 3;
  // Accept RGBA input by dropping alpha, since GL readbacks are usually RGBA.
  const channels = pixels.length / (width * height);
  if (channels !== 3 && channels !== 4) {
    throw new Error(`unexpected channel count ${channels}`);
  }
  const out = new Uint8Array(expected);
  let w = 0;
  for (let i = 0; i < width * height; i++) {
    out[w++] = pixels[i * channels];
    out[w++] = pixels[i * channels + 1];
    out[w++] = pixels[i * channels + 2];
  }
  return { data: out, size };
}

/** Fetch the grid entry at integer lattice coordinates. */
function entry(grid: LutGrid, r: number, g: number, b: number): Rgb {
  const { data, size } = grid;
  // Red fastest, then green, then blue — matches identity_grid in backend/lut.py.
  const idx = ((b * size + g) * size + r) * 3;
  return [data[idx], data[idx + 1], data[idx + 2]];
}

function lerp(a: number, b: number, t: number): number {
  return a + (b - a) * t;
}

function lerp3(a: Rgb, b: Rgb, t: number): Rgb {
  return [lerp(a[0], b[0], t), lerp(a[1], b[1], t), lerp(a[2], b[2], t)];
}

/**
 * Trilinearly sample the LUT for an input colour.
 *
 * Input and output are 0–255. Interpolates along red, then green, then blue, in the same
 * order as `apply_lut` in backend/lut.py.
 */
export function sampleLut(grid: LutGrid, rgb: Rgb): Rgb {
  const { size } = grid;
  const max = size - 1;

  // Guard against non-finite input: Math.min/max propagate NaN, which would poison the
  // interpolation and produce NaN pixels rather than a visible colour.
  const clamp01 = (v: number) => (Number.isFinite(v) ? Math.min(1, Math.max(0, v / 255)) : 0);
  const pos: Rgb = [clamp01(rgb[0]) * max, clamp01(rgb[1]) * max, clamp01(rgb[2]) * max];

  const lo = pos.map(Math.floor) as Rgb;
  const hi = lo.map(v => Math.min(v + 1, max)) as Rgb;
  const frac = [pos[0] - lo[0], pos[1] - lo[1], pos[2] - lo[2]] as Rgb;

  const c00 = lerp3(entry(grid, lo[0], lo[1], lo[2]), entry(grid, hi[0], lo[1], lo[2]), frac[0]);
  const c01 = lerp3(entry(grid, lo[0], hi[1], lo[2]), entry(grid, hi[0], hi[1], lo[2]), frac[0]);
  const c10 = lerp3(entry(grid, lo[0], lo[1], hi[2]), entry(grid, hi[0], lo[1], hi[2]), frac[0]);
  const c11 = lerp3(entry(grid, lo[0], hi[1], hi[2]), entry(grid, hi[0], hi[1], hi[2]), frac[0]);

  const c0 = lerp3(c00, c01, frac[1]);
  const c1 = lerp3(c10, c11, frac[1]);
  return lerp3(c0, c1, frac[2]);
}

/** Build an identity grid, matching backend/lut.py identity_grid. */
export function identityGrid(size: number): LutGrid {
  const data = new Uint8Array(size * size * size * 3);
  let i = 0;
  for (let b = 0; b < size; b++) {
    for (let g = 0; g < size; g++) {
      for (let r = 0; r < size; r++) {
        data[i++] = Math.round((r / (size - 1)) * 255);
        data[i++] = Math.round((g / (size - 1)) * 255);
        data[i++] = Math.round((b / (size - 1)) * 255);
      }
    }
  }
  return { data, size };
}
